spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration


logging:
  level:
    org.flywaydb: DEBUG